Test2 Lab: Temporary change to test rollback functionality

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -105,7 +105,7 @@ jobs:
       - name: Run post-deployment health check in Dev
         run: |
           echo "Checking health of Dev environment..."
-        # curl -f https://8000-port-icofesoidde2gav7.kk-lab-dev.kodekloud.com/health || exit 1
+          curl -f https://8000-port-xee3tsm7n5zcfy64.kk-lab-dev.kodekloud.com/health || exit 1
 
   deploy-prod:
     needs: deploy-dev  
@@ -124,12 +124,12 @@ jobs:
       - name: Run post-deployment health check in Production
         run: |
           echo "Checking health of Production..."
-        # curl -f https://8000-port-icofesoidde2gav7.kk-lab-dev.kodekloud.com/health || exit 1
+          curl -f http://your-dev-service-url/health || exit 1
 
-      # # 👇 Uncomment in "Rollback on Failure" 
-      # - name: Rollback if deployment fails
-      #   if: failure()
-      #   run: |
-      #     echo "Rolling back to previous version..."
-      #     docker pull ghcr.io/${{ github.repository }}/kodekloud-record-store-api:latest
-      #     # Deploy the last known good version
+      # 👇 Uncomment in "Rollback on Failure" 
+      - name: Rollback if deployment fails
+        if: failure()
+        run: |
+          echo "Rolling back to previous version..."
+          docker pull ghcr.io/${{ github.repository }}/kodekloud-record-store-api:latest
+          # Deploy the last known good version
